name: Hello to user

on: 
  workflow_call:
    inputs:
      user-name:
        required: false
        default: Junepil Lee
        type: string

jobs:
  reusable_workflow_job:
    runs-on: ubuntu-latest
    steps:
      - run: "echo Hello ${{ inputs.user-name }}?"
